# Generated by Django 3.2.6 on 2021-08-25 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctorClinics', '0003_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctorClinics.patient'),
        ),
    ]
