# Generated by Django 3.2.6 on 2021-08-25 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctorClinics', '0004_alter_clinic_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinics', to='doctorClinics.doctor'),
        ),
    ]
